version: 1.0.3.{build}
branches:
  only:
  - develop
  - master
image: Visual Studio 2019
configuration: Release
cache:
  - '%LocalAppData%\NuGet\v3-cache'
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  APPVEYOR_RDP_PASSWORD:
    secure: TLTj6is7gwncd5FVEw/Xzg==
before_build:
- cmd: nuget restore
build:
  project: Semiodesk.Trinity.sln
  publish_nuget: true
  verbosity: minimal
before_test:
- ps: ''
test:
  assemblies:
    only:
    - Build\Debug\test\Semiodesk.Trinity.Tests.exe